"""List of canonical names for conferences.

Keywords are ordered by increasing specificity.
Example:
  Security and Privacy (assumed IEEE S&P)
  Web 2.0 Security and Privacy (assumed W2SP)
"""

CONFERENCE_KEYWORDS = [
  [["Privacy Enhancing Technologies", "PET"],
    "Proceedings of the Privacy Enhancing Technologies Symposium"],
  [["World Wide Web", "WWW"], 
    "Proceedings of the International Conference on the World Wide Web"],
  [["Computer Security Applications", "ACSAC"],
    "Proceedings of the Annual Computer Security Applications Conference"],
  [["Communications Security", "CCS"],
    "Proceedings of the Conference on Computer and Communications Security"],
  [["Security and Privacy", "Security \\\& Privacy", "Security Privacy", "Oakland"],
    "Proceedings of the IEEE Symposium on Security and Privacy"],
  [["Web 2.0 Security and Privacy", "W2SP"],
    "Proceedings of the Workshop on Web 2.0 Security and Privacy"],
  [["IMC", "Internet Measurement"],
    "Proceedings of the ACM SIGCOM Internet Measurement Conference"],
  [["NDSS", "Network and Distributed System Security"],
    "Proceedings of the Network and Distributed System Security Conference"],
  [["NSDI", "Network System Design and Implementation"],
    "Proceedings of the Symposium on Network System Design and Implementation"],
  [["LEET", "Scale Exploits"], # Now defunct
    "Proceedings of the USENIX Workshop on Large-Scale Exploits and Emergent Threats"],
  [["Hotbot", "Hot Topics in Understanding Botnets"], # Now defunct
    "Proceedings of the USENIX Workshop on Hot Topics in Understanding Botnets"],
  [["WIFS", "Information Forensics and Security"],
    "Proceedings of the Workshop on Information Forensics and Security"],
  [["WEIS", "Economics of Information Security"],
    "Proceedings of the Workshop on Workshop on Economics of Information Security"],
  [["WOSN", "Workshop on Online Social Networks"],
    "Proceedings of the Workshop on Online Social Networks"],
  [["AIRWeb", "Adversarial Information Retrieval"],
    "Proceedings of SIGIR Workshop on Adversarial Information Retrieval on the Web"],
  [["ICWSM", "Weblogs and Social Media"],
    "Proceedings of the AAAI International Conference on Weblogs and Social Media"],
  [["Collaboration, Electronic", "CEAS", "Electronic Messaging"],
    "Proceedings of the Annual Collaboration, Electronic messaging, Anti-Abuse and Spam Conference"],
  [["Financial Cryptography", "FC"],
    "Proceedings of the International Conference on Financial Cryptography and Data Security"],
  [["OSDI", "Operating Systems Design"],
    "Proceedings of the Symposium on Operating Systems Design and Implementation"],
  [["eCrime", "eCRS"],
    "Proceedings of the IEEE eCrime Researchers Summit"],
  [["FTCS", "Symposium on Fault-Tolerant Computing"],
    "Proceedings of the International Symposium on Fault-Tolerant Computing"],
  [["Measurement and Modeling of Computer Systems"],
    "Proceedings of the ACM Conference on Measurement and Modeling of Computer Systems"],
  [["Management and Performance Evaluation"],
    "Proceedings of the International Conference on Management and Performance Evaluation of Computer Systems"],
  [["VLDB", "Very Large Data Bases"],
    "Proceedings of the International Conference on Very Large Data Bases"],
  [["PODC", "Principles of Distributed Computing"],
    "Proceedings of the Symposium on Principles of Distributed Computing"],
  [["Large Installation System Administration", "LISA"],
    "Proceedings of the Large Installation System Administration Conference"],
  [["Hot Topics in Networks", "Hotnets"],
    "Proceedings of the Workshop on Hot Topics in Networks"],
  [["Hot Topics in Operating", "Hotos"],
    "Proceedings of the Workshop on Hot Topics in Operating Systems"],
  [["Usenix annual", "Usenix Technical"],
    "Proceedings of the USENIX Annual Technical Conference"],
  [["Symposium on Computer Architecture", "ISCA"],
    "Proceedings of the International Symposium on Computer Architecture"],
  [["Principles of Programming Languages", "POPL"],
    "Proceedings of the Annual Symposium on Principles of Programming Languages"],
  [["International Information Security Conference"],
    "Proceedings of the IFIP International Information Security and Privacy Conference"],
  [["INFOCOM", "Computer and Communications Societies"],
    "Proceedings of the Annual Joint Conference of the IEEE Computer and Communications Societies"],
  [["SOSP", "Symposium on Operating Systems Principles"],
    "Proceedings of the ACM Symposium on Operating Systems Principles"],
  [["ASPLOS", "Architectural Support"],
    "Proceedings of the Symposium on Architectural Support for Programming Languages and Operating Systems"],
  [["Development in Information Retrieval"],
    "Proceedings of the Annual International ACM Conference on Research and Development in Information Retrieval"],
  [["Hypertext and Social"],
    "Proceedings of the ACM Conference on Hypertext and Social Media"],
  [["Malicious and Unwanted Software"],
    "Proceedings of the International Conference on Malicious and Unwanted Software"],
  [["PLDI", "Programming Language Design"],
    "Proceedings of the Conference on Programming Language Design and Implementation"],
  [["RAID", "Recent Advances"],
    "Proceedings of International Symposium on Recent Advances in Intrusion Detection"],
  [["ICML", "International Conference on Machine Learning"],
    "Proceedings of the International Conference on Machine Learning"],
  [["Economics and Computation"],
    "Proceedings of the ACM Conference on Economics and Computation"],
  [["KDD", "Knowledge Discovery"],
    "Proceedings of the SIGKDD International Conference on Knowledge Discovery and Data Mining"],
  [["ICDCS", "Distributed Computing Systems"],
    "Proceedings of the International Conference on Distributed Computing Systems"],
  [["PST", "Privacy Security and Trust"],
    "Proceedings of the Annual Conference on Privacy Security and Trust"],
  [["DIMVA", "Intrusions and Malware"],
    "Proceedings of the International Conference on Detection of Intrusions and Malware and Vulnerability Assessment"],
  [["Usenix Security", "Security Symposium", "usenix-security"],
    "Proceedings of the USENIX Security Symposium"]
]

